# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-15 13:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teryt_tree', '0006_auto_20170729_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('original_name', models.CharField(max_length=100)),
                ('original_pk', models.IntegerField(db_index=True)),
                ('detected_name', models.CharField(max_length=100)),
                ('detected_regon', models.CharField(max_length=14)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('original_teryt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teryt_tree.JednostkaAdministracyjna')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
