# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-15 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teryt_tree', '0006_auto_20170729_1659'),
        ('cityhalls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityhall',
            name='original_teryt',
        ),
        migrations.AddField(
            model_name='cityhall',
            name='original_simc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teryt_tree.SIMC'),
        ),
        migrations.AlterField(
            model_name='cityhall',
            name='original_pk',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
