# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teryt_tree', '0007_auto_20170815_1706'),
        ('cityhalls', '0003_auto_20170815_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityhall',
            name='original_simc',
        ),
        migrations.AddField(
            model_name='cityhall',
            name='original_terc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teryt_tree.JednostkaAdministracyjna'),
        ),
    ]
