# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teryt_tree', '0004_auto_20170712_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'ESPs',
                'verbose_name': 'ESP',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField()),
                ('epuap_id', models.CharField(help_text='Basic Institution ID in ePUAP', max_length=100, verbose_name='ePUAP ID')),
                ('regon', models.IntegerField(db_index=True, null=True, verbose_name='REGON  number')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Address')),
                ('postal_code', models.CharField(max_length=6, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('teryt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teryt_tree.JednostkaAdministracyjna')),
            ],
            options={
                'verbose_name_plural': 'Institutions',
                'verbose_name': 'Institution',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='esp',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution', verbose_name='Institution'),
        ),
    ]
