# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_auto_20170712_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='regon',
            field=models.CharField(db_index=True, max_length=20, null=True, verbose_name='REGON  number'),
        ),
    ]
