# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_auto_20170712_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp',
            name='active',
            field=models.BooleanField(default=True, help_text='Is the ESP active?', verbose_name='Active status'),
        ),
        migrations.AddField(
            model_name='institution',
            name='active',
            field=models.BooleanField(default=True, help_text='Is the institution active?', verbose_name='Active status'),
        ),
    ]
