# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 17:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_regon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regon',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Data for database search results REGON BIP1', null=True, verbose_name='Response data'),
        ),
    ]
