# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0008_auto_20170712_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='REGONError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('exception', models.CharField(max_length=200)),
                ('regon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institutions.REGON', verbose_name='REGON')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
