# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teryt_tree', '0003_auto_20161210_1515'),
        ('institutions', '0009_regonerror'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSTConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution', verbose_name='Institution')),
                ('jst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teryt_tree.JednostkaAdministracyjna', verbose_name='Administration division unit')),
            ],
            options={
                'verbose_name_plural': 'JSTConnections',
                'ordering': ['created'],
                'verbose_name': 'JSTConnection',
            },
        ),
        migrations.AlterModelOptions(
            name='regon',
            options={'ordering': ['created'], 'verbose_name': 'REGON', 'verbose_name_plural': 'REGONs'},
        ),
    ]
