# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0010_auto_20170712_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='teryt',
        ),
    ]
