# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 02:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0011_remove_institution_teryt'),
    ]

    operations = [
        migrations.CreateModel(
            name='RESP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Data from load RESP.xml', null=True, verbose_name='XML data')),
            ],
            options={
                'verbose_name_plural': 'RESPs',
                'verbose_name': 'RESP',
                'ordering': ['created'],
            },
        ),
        migrations.RemoveField(
            model_name='institution',
            name='address',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='city',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='slug',
        ),
        migrations.AlterField(
            model_name='regonerror',
            name='regon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.REGON', verbose_name='REGON'),
        ),
        migrations.AddField(
            model_name='resp',
            name='institution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution'),
        ),
    ]
