# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 04:43
from __future__ import unicode_literals

from django.db import migrations, models


def update_names(apps, schema_editor):
    for x in apps.get_model('institutions', 'regon').objects.exclude(data=None).iterator():
        x.name = x.data.get('nazwa', '')
        x.save()
    for x in apps.get_model('institutions', 'resp').objects.exclude(data=None).iterator():
        x.name = x.data.get('name', '')
        x.save()


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0013_auto_20170718_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='regon',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resp',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.RunPython(update_names)
    ]
