# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0014_auto_20170718_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regon',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='resp',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Name'),
        ),
    ]
