# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-30 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0015_auto_20170718_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regon',
            name='institution',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regon_data', to='institutions.Institution', verbose_name='Institution'),
        ),
    ]
