# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-30 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0016_auto_20170730_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regon',
            name='regon',
            field=models.CharField(db_index=True, default='', max_length=20, verbose_name='REGON  number'),
            preserve_default=False,
        ),
    ]
