# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-15 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teryt_tree', '0006_auto_20170729_1659'),
        ('institutions', '0017_auto_20170730_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='REGONJST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('jst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teryt_tree.JednostkaAdministracyjna')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='regon',
            name='regon',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='REGON  number'),
        ),
        migrations.AddField(
            model_name='regonjst',
            name='regon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='institutions.REGON'),
        ),
    ]
