# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-29 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='District name')),
                ('appeal', models.CharField(blank=True, max_length=100, verbose_name='Appeal name')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('postcode', models.CharField(max_length=6, verbose_name='Post code')),
                ('phone', models.CharField(max_length=100, verbose_name='Telephone')),
                ('fax', models.CharField(max_length=100, verbose_name='Telephone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courts.Court')),
            ],
            options={
                'verbose_name': 'Court',
                'verbose_name_plural': 'Courts',
                'ordering': ['created'],
            },
        ),
    ]
