# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-29 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Is court active?'),
        ),
    ]
