# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-29 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0015_auto_20170718_0525'),
        ('courts', '0002_court_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='REGONGuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('court', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courts.Court')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
